---
- name: Send SNS notification
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Publish message to SNS topic
      amazon.aws.sns:
        msg: "Build completed successfully"
        topic: "arn:aws:sns:ap-south-1:123456789012:myTopic"
        region: "ap-south-1"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "ap-south-1"
