---
- hosts: localhost
  gather_facts: false

  vars:
    topic_arn: "arn:aws:sns:ap-south-1:028112802802:jen-builds-01"   # replace
    region: "ap-south-1"

  tasks:
    - name: Send notification to SNS
      shell: |
        aws sns publish \
          --region "{{ region }}" \
          --topic-arn "{{ topic_arn }}" \
          --message "Test message from Ansible via Jenkins"
